{
 "title": "WMS History",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "status",
    "query": "{\"find\":\"terms\", \"field\": \"Status\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs by Status",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Status",
       "id": "9",
       "settings": {
        "min_doc_count": "1",
        "missing": "Other",
        "order": "desc",
        "orderBy": "_term",
        "size": "20"
       },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "10",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "Jobs",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Jobs by Status",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Status",
       "id": "9",
       "settings": {
        "min_doc_count": "1",
        "missing": "Other",
        "order": "desc",
        "orderBy": "_term",
        "size": "20"
       },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "10",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "Jobs",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$status Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "status",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of $status Jobs",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "15m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "Jobs",
         "hide": false,
         "id": "1",
         "type": "sum"
        },
        {
         "field": "1",
         "hide": true,
         "id": "3",
         "pipelineAgg": "1",
         "settings": { "model": "simple", "window": "5" },
         "type": "moving_avg"
        }
       ],
       "query": "Status: $status",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$status Jobs by All Users",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "User",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "Jobs", "id": "1", "type": "sum" }
       ],
       "query": "Status: ${status:lucene}",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$status Jobs by JobGroup",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "JobGroup",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "Jobs", "id": "1", "type": "sum" }
       ],
       "query": "Status: ${status:lucene}",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$status Jobs by JobSplitType",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "JobSplitType",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "Jobs", "id": "1", "type": "sum" }
       ],
       "query": "Status: ${status:lucene}",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$status Jobs by UserGroup",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "UserGroup",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "Jobs", "id": "1", "type": "sum" }
       ],
       "query": "Status: ${status:lucene}",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$status Jobs by Site",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Site",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "Jobs", "id": "1", "type": "sum" }
       ],
       "query": "Status: ${status:lucene}",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$status Jobs by MinorStatus",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "MinorStatus",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "Jobs", "id": "1", "type": "sum" }
       ],
       "query": "Status: ${status:lucene}",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}