{
 "title": "Demo Dashboard",
 "time": { "from": "2023-03-02T00:00:00.000Z", "to": "2023-03-02T23:59:59.000Z" },
 "panels": [
  {
   "title": "Production Jobs By Final Minor Status (MySQL)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nac_key_Job_FinalMinorStatus.value,\nac_bucket_Job.startTime as time,\nSUM(ac_bucket_Job.entriesInBucket) / ac_bucket_Job.bucketLength * 3600 as metric\nFROM\nac_bucket_Job,\nac_key_Job_JobType,\nac_key_Job_FinalMinorStatus\nWHERE ac_bucket_Job.startTime >= $__unixEpochFrom()\nAND ac_bucket_Job.startTime <= $__unixEpochTo()\nAND ( ac_key_Job_JobType.value in (\"10\", \"DataReconstruction\", \"DataReprocessing\", \"DataStripping\", \"DataSwimming\", \"Hospital\", \"MCReconstruction\", \"MCReprocessing\", \"MCSimulation\", \"MCStripping\", \"Merge\", \"MergeMDF\" ,\"private\", \"production\", \"reconstruction\", \"sam\", \"test\", \"unknown\", \"WGProduction\") )\nAND ac_bucket_Job.FinalMinorStatus = ac_key_Job_FinalMinorStatus.id\nAND ac_bucket_Job.JobType = ac_key_Job_JobType.id\nGROUP BY\nstartTime,\nac_key_Job_FinalMinorStatus.value,\nbucketlength"
    }
   ]
  },
  {
   "title": "User Jobs By Final Minor Status (MySQL)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n`ac_key_Job_FinalMinorStatus`.`value`,\n`ac_bucket_Job`.`startTime` as time,\nSUM(`ac_bucket_Job`.`entriesInBucket`) / `ac_bucket_Job`.`bucketLength` * 3600 as metric\nFROM\n`ac_bucket_Job`,\n`ac_key_Job_JobType`,\n`ac_key_Job_FinalMinorStatus`\nWHERE `ac_bucket_Job`.`startTime` >= $__unixEpochFrom()\nAND `ac_bucket_Job`.`startTime` <= $__unixEpochTo()\nAND ( `ac_key_Job_JobType`.`value` = \"User\")\nAND `ac_bucket_Job`.`FinalMinorStatus` = `ac_key_Job_FinalMinorStatus`.`id`\nAND `ac_bucket_Job`.`JobType` = `ac_key_Job_JobType`.`id`\nGROUP BY\nstartTime,\n`ac_key_Job_FinalMinorStatus`.value,\nbucketlength"
    }
   ]
  },
  {
   "title": "Job CPU Efficiency By JobType (MySQL)",
   "type": "status-history",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n`ac_key_Job_JobType`.`value`,\n`ac_bucket_Job`.`startTime` as time,\n100 * SUM(`ac_bucket_Job`.`CPUTime`) / SUM(`ac_bucket_Job`.`ExecTime`) / `ac_bucket_Job`.`bucketLength` * 3600 as metric\nFROM\n`ac_bucket_Job`,\n`ac_key_Job_JobType`\nWHERE\n`ac_bucket_Job`.`startTime` >= $__unixEpochFrom()\nAND `ac_bucket_Job`.`startTime` <= $__unixEpochTo()\nAND `ac_bucket_Job`.`JobType` = `ac_key_Job_JobType`.`id`\nGROUP BY\ntime,\n`ac_key_Job_JobType`.Value,\nbucketlength"
    }
   ]
  },
  {
   "title": "User Jobs By JobType (ElasticSearch)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "JobType",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Status: Done AND JobType: User",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "User Jobs By Final Minor Status (MySQL)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n`ac_key_DataOperation_Protocol`.`value`,\n`ac_bucket_DataOperation`.`startTime` as time,\n(SUM(`ac_bucket_DataOperation`.`TransferTotal`) - SUM(`ac_bucket_DataOperation`.`TransferOK`) ) / `ac_bucket_DataOperation`.`bucketLength` * 3600 AS metric\nFROM\n`ac_bucket_DataOperation`,\n`ac_key_DataOperation_Protocol`,\n`ac_key_DataOperation_FinalStatus`\nWHERE `ac_bucket_DataOperation`.`startTime` >= $__unixEpochFrom()\nAND `ac_bucket_DataOperation`.`startTime` <= $__unixEpochTo()\nAND ( `ac_key_DataOperation_FinalStatus`.`value` = \"Failed\" )\nAND `ac_bucket_DataOperation`.`Protocol` =\n`ac_key_DataOperation_Protocol`.`id`\nAND `ac_bucket_DataOperation`.`FinalStatus` = `ac_key_DataOperation_FinalStatus`.`id`\nGROUP BY\ntime,\n`ac_key_DataOperation_Protocol`.Value,\nbucketlength"
    }
   ]
  },
  {
   "title": "Pilots By Status (MySQL)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n`ac_key_Pilot_GridStatus`.`value`,\n`ac_bucket_Pilot`.`startTime` as time,\nSUM(`ac_bucket_Pilot`.`entriesInBucket`) / `ac_bucket_Pilot`.`bucketLength` * 3600 as metric\nFROM\n`ac_bucket_Pilot`,\n`ac_key_Pilot_GridStatus`\nWHERE\n`ac_bucket_Pilot`.`startTime` >= $__unixEpochFrom()\nAND `ac_bucket_Pilot`.`startTime` <= $__unixEpochTo()\nAND `ac_bucket_Pilot`.`GridStatus` = `ac_key_Pilot_GridStatus`.`id`\nGROUP BY\nstartTime,\n`ac_key_Pilot_GridStatus`.Value,\nbucketlength"
    }
   ]
  }
 ]
}