image: gitlab-registry.cern.ch/alu/dirac/docker-compose

services:
  - name: docker:dind

before_script:
  - "echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} ${CI_REGISTRY} --password-stdin"

variables:
  COMPOSE_HTTP_TIMEOUT: "360"

test:
  script:
    - "bash tests/CI/run_docker_setup"
  after_script:
    - "bash -c 'source tests/CI/utils.sh && getLogs'"
  artifacts:
    name: "logs_$CI_JOB_NAME"
    paths:
      - log_server_install.txt
      - log_server_tests.txt
      - log_client_install.txt
      - log_client_tests.txt
    expire_in: 1 week
    when: always
  except:
    - pushes


