{
 "title": "Data Management overview",
 "description": "Overview of the ongoing Data Management operations",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "destination",
    "label": "Destination",
    "query": "{\"find\": \"terms\", \"field\": \"Destination\" , \"size\":10000}"
   },
   {
    "name": "executionSite",
    "label": "ExecutionSite",
    "query": "{\"find\": \"terms\", \"field\": \"ExecutionSite\" , \"size\":10000}"
   },
   {
    "name": "user",
    "label": "User",
    "query": "{\"find\": \"terms\", \"field\": \"User\" , \"size\":10000}"
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "{\"find\": \"terms\", \"field\": \"Protocol\" , \"size\":10000 , \"query\":\"OperationType:se*\"}"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "{\"find\": \"terms\", \"field\": \"Source\" , \"size\":10000}"
   },
   {
    "name": "finalStatus",
    "label": "Status",
    "query": "{\"find\": \"terms\", \"field\": \"FinalStatus\" , \"size\":10000}"
   },
   {
    "name": "operationType",
    "label": "Operation",
    "query": "{\"find\": \"terms\", \"field\": \"OperationType\" , \"size\":10000}"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expression": "$TransferSize/$TransferTime", "type": "math" }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Data upload final status",
   "type": "piechart",
   "description": "Final status of se.putFile",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "FinalStatus",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND Destination:${destination} AND ExecutionSite:${executionSite} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed Data upload by Protocol",
   "type": "piechart",
   "description": "Final status of se.putFile",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful  Data upload by Protocol",
   "type": "piechart",
   "description": "Final status of se.putFile",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful  Data upload by User",
   "type": "piechart",
   "description": "Final status of se.putFile",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed  Data upload by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Cumulative uploaded data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Destination",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "TransferSize",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      { "field": "1", "id": "4", "type": "cumulative_sum" }
     ],
     "query": "OperationType:se.putFile AND Destination:${destination} AND ExecutionSite:${executionSite} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Cumulative uploaded data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ExecutionSite",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "TransferSize",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      { "field": "1", "id": "4", "type": "cumulative_sum" }
     ],
     "query": "OperationType:se.putFile AND Destination:${destination} AND ExecutionSite:${executionSite} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Data download final status",
   "type": "piechart",
   "description": "Final status of se.putFile",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "FinalStatus",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND Destination:${destination} AND ExecutionSite:${executionSite} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed Data Download by Protocol",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful  Data download by Protocol",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful  Data download by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed  Data download by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Cumulative downloaded data (source SE)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Source",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "TransferSize",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      { "field": "1", "id": "4", "type": "cumulative_sum" }
     ],
     "query": "OperationType:se.getFile AND ExecutionSite:${executionSite} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Cumulative downloaded data (execution site)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ExecutionSite",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "TransferSize",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      { "field": "1", "id": "4", "type": "cumulative_sum" }
     ],
     "query": "OperationType:se.getFile AND ExecutionSite:${executionSite} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Removal final status",
   "type": "piechart",
   "description": "Final status of se.putFile",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "FinalStatus",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.removeFile AND Destination:${destination} AND ExecutionSite:${executionSite} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed removal by Protocol",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.removeFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful  removal by Protocol",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.removeFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful  removal by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.removeFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed  removal by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.removeFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Data download", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": " Data download by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "FinalStatus",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND Destination:${destination} AND ExecutionSite:${executionSite} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful download throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite}  AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful download by source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Source",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed download by source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Source",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful download by protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed download by Protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful download by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed download by user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful download by ExecutionSite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ExecutionSite",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed download by ExecutionSite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ExecutionSite",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Data Upload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Data Upload by Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "FinalStatus",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND Destination:${destination} AND ExecutionSite:${executionSite} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful upload throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite}  AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful upload by destination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Destination",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed upload by destination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Destination",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful upload by protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite}  AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed upload by protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND  Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful upload by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite}  AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed upload by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "User",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite}  AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed upload by ExecutionSite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ExecutionSite",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Successful AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed upload by ExecutionSite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ExecutionSite",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${executionSite} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}