{
 "title": "Tier1 DMS",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "destination",
    "label": "Destination",
    "query": "{\"find\": \"terms\", \"field\": \"Destination\" , \"size\":10000}"
   },
   {
    "name": "executionSite",
    "label": "ExecutionSite",
    "query": "{\"find\": \"terms\", \"field\": \"ExecutionSite\" , \"size\":10000}"
   },
   {
    "name": "user",
    "label": "User",
    "query": "{\"find\": \"terms\", \"field\": \"User\" , \"size\":10000}"
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "{\"find\": \"terms\", \"field\": \"Protocol\" , \"size\":10000 , \"query\":\"OperationType:se*\"}"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "{\"find\": \"terms\", \"field\": \"Source\" , \"size\":10000}"
   },
   {
    "name": "finalStatus",
    "label": "Status",
    "query": "{\"find\": \"terms\", \"field\": \"FinalStatus\" , \"size\":10000}"
   },
   {
    "name": "operationType",
    "label": "Operation",
    "query": "{\"find\": \"terms\", \"field\": \"OperationType\" , \"size\":10000}"
   },
   {
    "name": "site",
    "label": "Site",
    "query": "LCG.CERN.cern,LCG.CNAF.it,LCG.IN2P3.fr,LCG.GRIDKA.de,LCG.PIC.es,LCG.RAL.uk,LCG.RRCKI.ru"
   }
  ]
 },
 "panels": [
  {
   "title": "Upload from site overwiew",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Upload status from ${site}",
   "type": "vonage-status-panel",
   "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 1 },
   "repeat": "site",
   "targets": [
    {
     "aggregation": "Avg",
     "alias": "Status",
     "bucketAggs": [
      { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "crit": 0.8,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metrics": [
      {
       "field": "TransferTotal",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      {
       "field": "TransferOK",
       "hide": true,
       "id": "6",
       "type": "sum"
      },
      {
       "id": "7",
       "pipelineVariables": [
        { "name": "all", "pipelineAgg": "1" },
        { "name": "ok", "pipelineAgg": "6" }
       ],
       "settings": { "script": "params.ok / params.all" },
       "type": "bucket_script"
      }
     ],
     "query": "OperationType:se.putFile  AND Destination:${destination} AND ExecutionSite:${site} AND FinalStatus:${finalStatus} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp",
     "units": "percentunit",
     "valueHandler": "Number Threshold",
     "warn": 0.95
    }
   ]
  },
  { "title": "${site}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "site" },
  {
   "title": "Successful upload from ${site}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Destination",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Successful AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Destination:${destination}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed upload from ${site}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Destination",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile  AND FinalStatus:Failed AND Destination:${destination} AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful download from ${site}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Source",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failed download from ${site}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Source",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Failed AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Download by protocol at ${site}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "FinalStatus",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Upload by protocol at ${site}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "FinalStatus",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Destination:${destination} AND FinalStatus:${finalStatus}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "${protocol} upload performance at ${site}",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 34 },
   "repeat": "protocol",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "FinalStatus",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.putFile AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Destination:${destination} AND FinalStatus:${finalStatus}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "${protocol} download performance at ${site}",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 42 },
   "repeat": "protocol",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "FinalStatus",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "TransferTotal", "id": "1", "type": "sum" }
     ],
     "query": "OperationType:se.getFile AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Source:${source} AND FinalStatus:${finalStatus}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Upload throughput from ${site}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "settings": { "size": "500" },
       "type": "raw_data"
      }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:Successful AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Destination:${destination}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Download throughput from ${site}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "settings": { "size": "500" },
       "type": "raw_data"
      }
     ],
     "query": "OperationType:se.getFile AND FinalStatus:Successful AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Upload from ${site}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    { "expression": "1-$TransferOK/$TransferTotal", "type": "math" }
   ]
  },
  {
   "title": "Upload from ${site}",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Destination",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "9", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "TransferOK",
       "hide": true,
       "id": "4",
       "settings": { "missing": "-1" },
       "type": "sum"
      },
      {
       "field": "TransferTotal",
       "hide": true,
       "id": "7",
       "type": "sum"
      },
      {
       "id": "8",
       "pipelineVariables": [
        { "name": "ok", "pipelineAgg": "4" },
        { "name": "all", "pipelineAgg": "7" }
       ],
       "settings": { "script": "params.ok / params.all" },
       "type": "bucket_script"
      }
     ],
     "query": "OperationType:se.putFile AND FinalStatus:${finalStatus} AND ExecutionSite:${site} AND Protocol:${protocol} AND User:${user} AND Destination:${destination}",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}