#!/usr/bin/env bash
# This file contains all the environment variables necessary to run a full integration test

export DEBUG=${DEBUG:-True}

# Settings for external services

# MYSQL Settings
export DB_USER=${DB_USER:-Dirac}
export DB_PASSWORD=${DB_PASSWORD:-Dirac}
export DB_ROOTUSER=${DB_ROOTUSER:-root}
export DB_ROOTPWD=${DB_ROOTPWD:-password}
export DB_HOST=${DB_HOST:-mysql}
export DB_PORT=${DB_PORT:-3306}

# ElasticSearch settings
export NoSQLDB_HOST=${NoSQLDB_HOST:-elasticsearch}
export NoSQLDB_PORT=${NoSQLDB_PORT:-9200}

# Hostnames
export SERVER_HOST=${SERVER_HOST:-server}
export CLIENT_HOST=${CLIENT_HOST:-client}

# Settings for DIRAC installation
export PRERELEASE=${PRERELEASE:-}
export DIRAC_RELEASE=${DIRAC_RELEASE:-}
export DIRACBRANCH=${DIRACBRANCH:-}

# repository to get tests and install scripts from
export TESTREPO=${TESTREPO:-antolu}
export TESTBRANCH=${TESTBRANCH:-ci}

export DIRACOSVER=${DIRACOSVER:-master}
export DIRACOS_TARBALL_PATH=${DIRACOS_TARBALL_PATH:-}

# Versions of external services
export MYSQL_VER=${MYSQL_VER:-5.7}
export ES_VER=${ES_VER:-6.6.0}

# Optional parameters
export ALTERNATIVE_MODULES=${ALTERNATIVE_MODULES:-}

# Test specific variables
export DOCKER_USER=dirac
export USER_HOME=/home/${DOCKER_USER}
export WORKSPACE=$USER_HOME
