#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-externals-versions,v 1.1 2008/08/24 15:40:36 paterson Exp $
# File :   dirac-admin-externals-versions
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-admin-externals-versions,v 1.1 2008/08/24 15:40:36 paterson Exp $"
__VERSION__ = "$Revision: 1.1 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

diracAdmin = DiracAdmin()
diracAdmin.getExternalPackageVersions()
DIRAC.exit(0)

