#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-wms-job-peek,v 1.1 2008/02/11 09:36:20 paterson Exp $
__RCSID__ = "$Id: dirac-wms-job-peek,v 1.1 2008/02/11 09:36:20 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s <JobID>' %(argv[0])
  sys.exit(2)

if len(sys.argv)!=2:
  usage(sys.argv)

from DIRAC.Interfaces.API.Dirac                          import Dirac
dirac=Dirac()
try:
  jobID = int(sys.argv[1])
except Exception,x:
  print 'Expected string for jobID'
  sys.exit(2)

result = dirac.peek(jobID)
if result['OK']:
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)