#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-wms-job-submit,v 1.2 2008/04/17 08:27:17 rgracian Exp $
# File :   dirac-production-job-submit
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-wms-job-submit,v 1.2 2008/04/17 08:27:17 rgracian Exp $"
__VERSION__ = "$Revision: 1.2 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.Dirac                              import Dirac

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <Path to JDL file> |[<Path to JDL file>]' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) < 1:
  usage()
  
dirac=Dirac()
exitCode = 0

for jdl in args:

  result = dirac.submit(jdl)
  if result['OK']:
    print 'JobID = %s' %(result['Value'])
  else:
    print result['Message']
    exitCode = 2

DIRAC.exit(exitCode)