#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-get-site-mask,v 1.3 2008/08/26 17:42:24 paterson Exp $
# File :   dirac-admin-get-site-mask
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-admin-get-site-mask,v 1.3 2008/08/26 17:42:24 paterson Exp $"
__VERSION__ = "$Revision: 1.3 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

diracAdmin = DiracAdmin()

result = diracAdmin.getSiteMask(printOutput=True)
if result['OK']:
  DIRAC.exit(0)
else:
  print result['Message']
  DIRAC.exit(2)

