#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-dms-lfn-accessURL,v 1.1 2008/05/20 17:38:16 paterson Exp $
# File :   dirac-dms-lfn-accessURL
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-dms-lfn-accessURL,v 1.1 2008/05/20 17:38:16 paterson Exp $"
__VERSION__ = "$Revision: 1.1 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.Dirac                         import Dirac

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <LFN> <SE>' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) < 2:
  usage()

if len(args) > 2:
  print 'Only one LFN SE pair will be considered'

dirac = Dirac()
exitCode = 0
errorList = []

result = dirac.getAccessURL(args[0],args[1],printOutput=True)
if not result['OK']:
  errorList.append( (lfn, result['Message']) )
  exitCode = 2

for error in errorList:
  print "ERROR %s: %s" % error

DIRAC.exit(exitCode)