#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-allow-site,v 1.3 2008/04/17 08:27:16 rgracian Exp $
# File :   dirac-admin-allow-site
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-admin-allow-site,v 1.3 2008/04/17 08:27:16 rgracian Exp $"
__VERSION__ = "$Revision: 1.3 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <DIRAC site name> [<DIRAC site name>]' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) < 1:
  usage()
  
diracAdmin = DiracAdmin()
exitCode = 0
for site in args:
  try:
    site = str(site)
  except Exception,x:
    print 'Expected string for DIRAC site name', site
    exitCode = 2
    continue

  result = diracAdmin.addSiteInMask(site)
  if not result['OK']:
    print result['Message']
    exitCode = 2

DIRAC.exit(exitCode)
