#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-pilot-summary,v 1.1 2008/02/08 18:15:54 paterson Exp $
__RCSID__ = "$Id: dirac-admin-pilot-summary,v 1.1 2008/02/08 18:15:54 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s' %(argv[0])
  sys.exit(2)

if len(sys.argv)!=1:
  usage(sys.argv)

from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin
diracAdmin = DiracAdmin()
result = diracAdmin.getPilotSummary()
if result['OK']:
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)

