#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-production-submit,v 1.3 2008/02/18 11:04:21 paterson Exp $
__RCSID__ = "$Id: dirac-production-submit,v 1.3 2008/02/18 11:04:21 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s <ProductionID> <NumberOfJobs> |Optional| <DIRAC Site Name>' %(argv[0])
  print sys.argv
  sys.exit(2)

if len(sys.argv)<3:
  usage(sys.argv)
print sys.argv
from DIRAC.Interfaces.API.DiracProduction import DiracProduction
diracProd=DiracProduction()

try:
  prodID = str(sys.argv[1])
except Exception,x:
  print 'Expected string for production identifier'
  sys.exit(2)

try:
  jobs = int(sys.argv[2])
except Exception,x:
  print 'Expected integer for number of jobs'
  sys.exit(2)

site=''
if len(sys.argv)>=4:
  try:
    site = str(sys.argv[3])
    print 'Destination site = %s' %site
  except Exception,x:
    print 'Expected string for DIRAC site name'
    sys.exit(2)

result = diracProd.submitProduction(prodID,jobs,site)
if result['OK']:
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)