#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-wms-job-get-output,v 1.1 2008/02/08 17:38:34 paterson Exp $
__RCSID__ = "$Id: dirac-wms-job-get-output,v 1.1 2008/02/08 17:38:34 paterson Exp $"
import sys,os

def usage(argv):
  print 'Usage: %s <JobID>' %(argv[0])
  sys.exit(2)

if len(sys.argv)!=2:
  usage(sys.argv)

from DIRAC.Interfaces.API.Dirac                          import Dirac
dirac=Dirac()
try:
  job = int(sys.argv[1])
except Exception,x:
  print 'Expected integer for jobID'
  sys.exit(2)

result = dirac.getOutputSandbox(job)
if result['OK']:
  if os.path.exists('%s' %job):
    print 'Job output sandbox retrieved in %s/' %(job)
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)