#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-wms-job-reschedule,v 1.1 2008/02/08 16:44:57 paterson Exp $
__RCSID__ = "$Id: dirac-wms-job-reschedule,v 1.1 2008/02/08 16:44:57 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s <JobID>' %(argv[0])
  sys.exit(2)

if len(sys.argv)!=2:
  usage(sys.argv)

from DIRAC.Interfaces.API.Dirac                          import Dirac
dirac=Dirac()
try:
  job = int(sys.argv[1])
except Exception,x:
  print 'Expected integer for jobID'
  sys.exit(2)

result = dirac.reschedule(job)
if result['OK']:
  print 'Rescheduled job %s' %(result['Value'][0])
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)