#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-dms-lfn-replicas,v 1.1 2008/02/08 19:27:56 paterson Exp $
__RCSID__ = "$Id: dirac-dms-lfn-replicas,v 1.1 2008/02/08 19:27:56 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s <LFN>' %(argv[0])
  sys.exit(2)

if len(sys.argv)!=2:
  usage(sys.argv)

from DIRAC.Interfaces.API.Dirac                          import Dirac
dirac=Dirac()
try:
  lfn = str(sys.argv[1])
except Exception,x:
  print 'Expected string for LFN'
  sys.exit(2)

result = dirac.getReplicas(lfn)
if result['OK']:
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)