#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-reset-job,v 1.1 2008/02/08 18:37:13 paterson Exp $
__RCSID__ = "$Id: dirac-admin-reset-job,v 1.1 2008/02/08 18:37:13 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s <JobID>' %(argv[0])
  sys.exit(2)

if len(sys.argv)!=2:
  usage(sys.argv)

from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin
diracAdmin = DiracAdmin()
try:
  job = int(sys.argv[1])
except Exception,x:
  print 'Expected integer for jobID'
  sys.exit(2)

result = diracAdmin.resetJob(job)
if result['OK']:
  print 'Reset Job %s' %(job)
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)