#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-get-proxy,v 1.1 2008/02/08 18:30:05 paterson Exp $
__RCSID__ = "$Id: dirac-admin-get-proxy,v 1.1 2008/02/08 18:30:05 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s <DN> <DIRAC proxy group>' %(argv[0])
  sys.exit(2)

if len(sys.argv)!=3:
  usage(sys.argv)

from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin
diracAdmin = DiracAdmin()
try:
  dn = str(sys.argv[1])
  group = str(sys.argv[2])
except Exception,x:
  print 'Expected strings for DN and proxy group'
  sys.exit(2)

result = diracAdmin.getProxy(dn,group)
if result['OK']:
  print 'Proxy file retrieved at:\n%s' %(result['Value'])
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)