#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-production-list-all,v 1.2 2008/04/17 08:27:16 rgracian Exp $
# File :   dirac-production-list-all
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-production-list-all,v 1.2 2008/04/17 08:27:16 rgracian Exp $"
__VERSION__ = "$Revision: 1.2 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.DiracProduction                    import DiracProduction

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

diracProd = DiracProduction()

result = diracProd.getAllProductions(printOutput=True)
if result['OK']:
  DIRAC.exit(0)
elif result.has_key('Message'):
  print 'Listing productions failed with message:\n%s' %(result['Message'])
  DIRAC.exit(2)
else:
  print 'Null result for getAllProductions() call'
  DIRAC.exit(2)