#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-dms-add-file,v 1.1 2008/05/30 16:26:08 paterson Exp $
# File :   dirac-dms-add-file
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-dms-add-file,v 1.1 2008/05/30 16:26:08 paterson Exp $"
__VERSION__ = "$Revision: 1.1 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.Dirac                       import Dirac

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <LFN> <FILE PATH> <DIRAC SE> [<GUID>]' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) < 3 or len(args) > 4:
  usage()

guid = None
if len(args)>3:
  guid = args[3]

dirac = Dirac()
exitCode = 0
result = dirac.addFile(args[0],args[1],args[2],guid,printOutput=True)
if not result['OK']:
  print 'ERROR %s' %(result['Message'])
  exitCode = 2

DIRAC.exit(exitCode)