#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-get-pilot-output,v 1.2 2008/04/17 07:05:09 rgracian Exp $
# File :   dirac-admin-get-pilot-output
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-admin-get-pilot-output,v 1.2 2008/04/17 07:05:09 rgracian Exp $"
__VERSION__ = "$Revision: 1.2 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <Grid pilot reference> [<Grid pilot reference>]' %(Script.scriptName)
  DIRAC.exit(2)

if len(args)!=1:
  usage()
  
diracAdmin = DiracAdmin()
exitCode = 0
for gridID in args:
  try:
    gridID = str(gridID)
  except Exception,x:
    print 'Expected string for Grid pilot reference', gridID
    exitCode = 2

  result = diracAdmin.getPilotOutput(gridID)
  if not result['OK']:
    print result['Message']
    exitCode = 2

DIRAC.exit(exitCode)