#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-ban-site,v 1.4 2008/04/17 13:10:03 rgracian Exp $
# File :   dirac-admin-ban-site
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-admin-ban-site,v 1.4 2008/04/17 13:10:03 rgracian Exp $"
__VERSION__ = "$Revision: 1.4 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <DIRAC site name> [<DIRAC site name>]' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) < 1:
  usage()
  
diracAdmin = DiracAdmin()
exitCode = 0
errorList = []

for site in args:

  result = diracAdmin.banSiteFromMask(site)
  if not result['OK']:
    errorList.append( (site, result['Message']) )
    exitCode = 2

for error in errorList:
  print "ERROR %s: %s" % error

DIRAC.exit(exitCode)