#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-get-proxy,v 1.2 2008/04/17 08:27:17 rgracian Exp $
# File :   dirac-admin-get-proxy
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-admin-get-proxy,v 1.2 2008/04/17 08:27:17 rgracian Exp $"
__VERSION__ = "$Revision: 1.2 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <DN> <DIRAC group>' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) != 2:
  usage()
  
diracAdmin = DiracAdmin()

try:
  dn = str(args[0])
  group = str(args[1])
except Exception,x:
  print 'Expected strings for DN and proxy group', args[0], args[1]
  DIRAC.exit(2)

result = diracAdmin.getProxy(dn,group)
if result['OK']:
  print 'Proxy file retrieved at:\n%s' %(result['Value'])
  DIRAC.exit(0)
else:
  print result['Message']
  DIRAC.exit(2)