#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-ban-site,v 1.9 2008/09/14 22:30:10 paterson Exp $
# File :   dirac-admin-ban-site
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-admin-ban-site,v 1.9 2008/09/14 22:30:10 paterson Exp $"
__VERSION__ = "$Revision: 1.9 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script

Script.registerSwitch( "", "comment=", "To add a comment string when allowing sites" )
Script.parseCommandLine( ignoreErrors = True )

from DIRAC.Interfaces.API.DiracAdmin import DiracAdmin
from DIRAC import gConfig

import time

comment = None
for switch in Script.getUnprocessedSwitches():
  if switch[0].lower()=="comment":
    comment = switch[1]

args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <DIRAC site name> [<DIRAC site name>] --comment="<COMMENT>"' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) < 1:
  usage()

diracAdmin = DiracAdmin()
exitCode = 0
errorList = []
address = gConfig.getValue('/Operations/EMail/Production','')
setup = gConfig.getValue('/DIRAC/Setup','')
if not address or not setup:
  print 'ERROR: Could not contact Configuration Service'
  exitCode = 2
  DIRAC.exit(exitCode)

userName = diracAdmin._getCurrentUser()
if not userName['OK']:
  print 'ERROR: Could not obtain current username from proxy'
  exitCode = 2
  DIRAC.exit(exitCode)
userName = userName['Value']

if not comment:
  comment = 'No comment supplied.'

for site in args:
  result = diracAdmin.banSiteFromMask(site,printOutput=True,comment)
  if not result['OK']:
    errorList.append( (site, result['Message']) )
    exitCode = 2
  else:
    subject = '%s is banned for %s setup' %(site,setup)
    body = 'Site %s is removed from site mask for %s setup by %s on %s.\n\n' %(site,setup,userName,time.asctime())
    body += 'Comment:\n%s' %comment
    result = diracAdmin.sendMail(address,subject,body)

for error in errorList:
  print "ERROR %s: %s" % error

DIRAC.exit(exitCode)
