#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-get-pilot-output,v 1.1 2008/02/11 18:05:14 paterson Exp $
__RCSID__ = "$Id: dirac-admin-get-pilot-output,v 1.1 2008/02/11 18:05:14 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s <Grid pilot reference>' %(argv[0])
  sys.exit(2)

if len(sys.argv)!=2:
  usage(sys.argv)

from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin
diracAdmin = DiracAdmin()
try:
  gridID = str(sys.argv[1])
except Exception,x:
  print 'Expected string for Grid pilot reference'
  sys.exit(2)

result = diracAdmin.getPilotOutput(gridID)
if result['OK']:
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)