#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-wms-job-status,v 1.2 2008/04/17 08:27:16 rgracian Exp $
# File :   dirac-production-job-status
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-wms-job-status,v 1.2 2008/04/17 08:27:16 rgracian Exp $"
__VERSION__ = "$Revision: 1.2 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.Dirac                              import Dirac

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <JobID> |[<JobID>]' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) < 1:
  usage()
  
dirac=Dirac()
exitCode = 0

for job in args:
  try:
    job = int(job)
  except Exception,x:
    print 'Expected integer for jobID', job
    exitCode = 2
    continue

  result = dirac.status(job)
  if result['OK']:
    print job, result['Value']
  else:
    print job, result['Message']
    exitCode = 2

DIRAC.exit(exitCode)