#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-production-site-summary,v 1.1 2008/04/16 14:34:44 paterson Exp $
__RCSID__ = "$Id: dirac-production-site-summary,v 1.1 2008/04/16 14:34:44 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s <PRODUCTION_ID> |Optional| <DIRAC Site Name>' %(argv[0])
  sys.exit(2)

if len(sys.argv)<2:
  usage(sys.argv)

from DIRAC.Interfaces.API.DiracProduction import DiracProduction
diracProd=DiracProduction()
prodID = sys.argv[1]
if not type(prodID)==type(long(1)):
  try:
    prodID = str(prodID)
  except Exception,x:
    print 'Expected long, string or int type for production identifier'
    sys.exit(2)

site=None
if len(sys.argv)>2:
  site = sys.argv[2]
  if not type(site)==type(" "):
    try:
      site = str(site)
    except Exception,x:
      print 'Expected string for DIRAC site name'
      sys.exit(2)

result = diracProd.getProductionSiteSummary(prodID,site,printOutput=True)
if result['OK']:
  sys.exit(0)
elif result.has_key('Message'):
  print 'Getting production site summary failed with message:\n%s' %(result['Message'])
  sys.exit(2)
else:
  print 'Null result for getProductionSiteSummary() call'
  sys.exit(2)