#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-reset-job,v 1.3 2008/04/17 13:10:03 rgracian Exp $
# File :   dirac-admin-reset-job
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-admin-reset-job,v 1.3 2008/04/17 13:10:03 rgracian Exp $"
__VERSION__ = "$Revision: 1.3 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <JobID> [<JobID>]' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) < 1:
  usage()
  
diracAdmin = DiracAdmin()
exitCode = 0
errorList = []

for job in args:

  try:
    job = int(job)
  except Exception,x:
    errorList.append( ( 'Expected integer for jobID', job ) )
    exitCode = 2
    continue

  result = diracAdmin.resetJob(job)
  if result['OK']:
    print 'Reset Job %s' %(job)
  else:
    errorList.append( (job, result['Message']) )
    exitCode = 2

for error in errorList:
  print "ERROR %s: %s" % error

DIRAC.exit(exitCode)