#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-admin-upload-proxy,v 1.1 2008/02/08 18:17:11 paterson Exp $
__RCSID__ = "$Id: dirac-admin-upload-proxy,v 1.1 2008/02/08 18:17:11 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s <DIRAC proxy group>' %(argv[0])
  sys.exit(2)

if len(sys.argv)!=2:
  usage(sys.argv)

from DIRAC.Interfaces.API.DiracAdmin                         import DiracAdmin
diracAdmin = DiracAdmin()
try:
  group = str(sys.argv[1])
except Exception,x:
  print 'Expected string for DIRAC proxy group'
  sys.exit(2)

result = diracAdmin.uploadProxy(group)
if result['OK']:
  print 'Proxy uploaded for group %s' %(group)
  sys.exit(0)
else:
  print result['Message']
  sys.exit(2)