#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-production-site-summary,v 1.2 2008/04/17 08:27:17 rgracian Exp $
# File :   dirac-production-site-summary
# Author : Stuart Paterson
########################################################################
__RCSID__   = "$Id: dirac-production-site-summary,v 1.2 2008/04/17 08:27:17 rgracian Exp $"
__VERSION__ = "$Revision: 1.2 $"
from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.Interfaces.API.DiracProduction                    import DiracProduction

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()

def usage():
  print 'Usage: %s <Production ID> [<DIRAC Site>]' %(Script.scriptName)
  DIRAC.exit(2)

if len(args) < 1:
  usage()
  
diracProd = DiracProduction()
prodID = args[0]

site = None
if len(args) = 2:
  site = args[2]

result = diracProd.getProductionSiteSummary(prodID,site,printOutput=True)
if result['OK']:
  DIRAC.exit(0)
elif result.has_key('Message'):
  print 'Getting production site summary failed with message:\n%s' %(result['Message'])
  DIRAC.exit(2)
else:
  print 'Null result for getProductionSiteSummary() call'
  DIRAC.exit(2)