#!/usr/bin/env python
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/Interfaces/scripts/Attic/dirac-production-list-all,v 1.1 2008/04/14 10:57:36 paterson Exp $
__RCSID__ = "$Id: dirac-production-list-all,v 1.1 2008/04/14 10:57:36 paterson Exp $"
import sys

def usage(argv):
  print 'Usage: %s' %(argv[0])
  sys.exit(2)

if len(sys.argv)>1:
  usage(sys.argv)

from DIRAC.Interfaces.API.DiracProduction import DiracProduction
diracProd=DiracProduction()

result = diracProd.getAllProductions(printOutput=True)
if result['OK']:
  sys.exit(0)
elif result.has_key('Message'):
  print 'Listing productions failed with message:\n%s' %(result['Message'])
  sys.exit(2)
else:
  print 'Null result for getAllProductions() call'
  sys.exit(2)