#!/bin/bash                                             
return_running()                                        
{                                                       
    local q;                                            
    local running;                                      
    let running=0;                                      
    for i in `ls -1 $1`; do                             
        test_pid=`cat $1/$i/pid`                        
        q=`ps -p $test_pid | wc -l`                     
        if (( $q == 2 )); then                          
             let running=running+1                      
        fi                                              
    done                                                
    echo -n $running                                    
}                                                       

run_job()
{
mkdir -p $3/$2
export SSHCE_PILOTREF=$2
$1 1>$3/$2/std.out 2>$3/$2/std.err &
echo $! > $3/$2/pid
echo $2
exit 0
}
test_pid_if_running()
{
    local q;
    q=`ps -p $1 | wc -l`
    if (( $q == 2 )); then
        echo -n "$2-R";
        return;
    fi
    echo -n "$2-D";
}
case "$1" in
    "dynamic_info")
        return_running $2;
        exit;;
    "run_job")
        run_job $2 $3 $4;
        exit;;
    "job_status")
        for stamp in `echo $3 | tr '#' ' '`; do
            test_pid_if_running `cat $2/$stamp/pid` $stamp;
            echo -n "#";
        done

        echo -n;
        exit ;;
esac
