"""
It is used to test the MonitoringReporter.
It requires MonitoringDB which is based on elasticsearch and MQ which is optional...

CS (not strictly necessary):

Systems
{
  Monitoring
  {
     Certification
     {
      Databases
      {
        MonitoringDB
        {
          Host = localhost
          Port = 9200
        }
      }
    }
  }
}

If you want to test with MQ:

Resources
{
  MQServices
  {
    Monitoring
    {
      MQType = Stomp
      VHost = /
      Host = xxxx.cern.ch
      Port = 61613
      User = username
      Password = xxxx
      Queues
      {
        QueueName
        {
          Acknowledgement = True
        }
      }
    }
  }
}

"""
# TODO: use WMSHistory_testData.json as in Test_MonitoringDB.py

# pylint: disable=invalid-name,wrong-import-position
import DIRAC

DIRAC.initialize()  # Initialize configuration

from DIRAC import gLogger
from DIRAC.MonitoringSystem.Client.MonitoringReporter import MonitoringReporter
from DIRAC.MonitoringSystem.Client import DataOperationSender

gLogger.setLevel("INFO")

wmsMonitoringReporter = MonitoringReporter(monitoringType="WMSHistory")
componentMonitoringReporter = MonitoringReporter(monitoringType="ComponentMonitoring")
pilotMonitoringReporter = MonitoringReporter(monitoringType="PilotSubmissionMonitoring")

data = [
    {
        "Status": "Waiting",
        "Jobs": 2,
        "timestamp": 1458130176,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.GRIDKA.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049848",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458130176,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.PIC.es",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "olupton",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458130176,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "olupton",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458130176,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049845",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 34,
        "timestamp": 1458141578,
        "JobSplitType": "DataStripping",
        "MinorStatus": "unset",
        "Site": "Group.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050299",
        "UserGroup": "lhcb_data",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 120,
        "timestamp": 1458141578,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.CERN.ch",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "mvesteri",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458141578,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049845",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 2,
        "timestamp": 1458141578,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049848",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458141578,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050286",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 95,
        "timestamp": 1458199202,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "Multiple",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "mamartin",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 3,
        "timestamp": 1458199202,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "Multiple",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "olupton",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 129,
        "timestamp": 1458199202,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "Multiple",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049844",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 5,
        "timestamp": 1458217812,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050232",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 7,
        "timestamp": 1458217812,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050234",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458217812,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 1,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050236",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 3,
        "timestamp": 1458217812,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050238",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 2,
        "timestamp": 1458217812,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050248",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 12,
        "timestamp": 1458218413,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050248",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 5,
        "timestamp": 1458218413,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050250",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 4,
        "timestamp": 1458218413,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050251",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458218413,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050280",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 24,
        "timestamp": 1458219012,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.NIKHEF.nl",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050248",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 3,
        "timestamp": 1458219012,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.NIKHEF.nl",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050251",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458222013,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.Bologna.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050303",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 7,
        "timestamp": 1458222013,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.Bristol.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "clangenb",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 2,
        "timestamp": 1458222013,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.Bristol.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "mrwillia",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458222013,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.Bari.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050244",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 11,
        "timestamp": 1458222013,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.Bari.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050246",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 22,
        "timestamp": 1458222013,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.Bari.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050248",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 23,
        "timestamp": 1458225013,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.DESYZN.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049844",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 18,
        "timestamp": 1458225013,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.DESYZN.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049847",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458225013,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.DESYZN.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050238",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458225013,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.DESYZN.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050246",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RRCKI.ru",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050243",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RRCKI.ru",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050251",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.RRCKI.ru",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050256",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050229",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050241",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050243",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 2,
        "timestamp": 1458226213,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050247",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
]

# This dataset is used for the ComponentMonitoringType as the data which gets stored in this type
# is usually with these type of fields.
activityMonitoringData = [
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
    {
        "site": "dirac-dev",
        "componentType": "service",
        "component": "Framework_SystemAdministrator",
        "componentLocation": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213,
    },
]
# Test data for the PilotMonitoring type
pilotMonitoringData = [
    {
        "HostName": "lhcbvoboxcertif00.cern.ch",
        "SiteDirector": "SiteDirector-CERN",
        "Site": "LCG.CERN.cern",
        "CE": "ce503.cern.ch",
        "Queue": "ce503.cern.ch:ce503.cern.ch-condor",
        "Status": "failed",
        "NumTotal": "10",
        "NumSucceded": "3",
        "timestamp": 1458226213,
    },
    {
        "HostName": "lhcbvoboxcertif00.cern.ch",
        "SiteDirector": "SiteDirector-CNAF",
        "Site": "LCG.CNAF.it",
        "CE": "ce504.cern.ch",
        "Queue": "ce504.cern.ch:ce504.cern.ch-condor",
        "Status": "failed",
        "NumTotal": "7",
        "NumSucceded": "1",
        "timestamp": 1458226213,
    },
]

dataOpMonitoringData = [
    {
        "OperationType": "se.getFile",
        "User": "rpozzi",
        "ExecutionSite": "",
        "Source": "CertificationSandboxSE",
        "Destination": "LCG.PIC.es",
        "Protocol": "dips",
        "FinalStatus": "Successful",
        "TransferSize": 3,
        "TransferTime": 1458226213,
        "RegistrationTime": 1458226213,
        "TransferOK": 20,
        "TransferTotal": 50,
        "RegistrationOK": 10,
        "RegistrationTotal": 40,
    },
    {
        "OperationType": "se.getFile",
        "User": "fstagni",
        "ExecutionSite": "",
        "Source": "Failed",
        "Destination": "LCG.PIC.es",
        "Protocol": "dips",
        "FinalStatus": "Failed",
        "TransferSize": 3,
        "TransferTime": 1458226213,
        "RegistrationTime": 1458226213,
        "TransferOK": 6,
        "TransferTotal": 26,
        "RegistrationOK": 3,
        "RegistrationTotal": 35,
    },
]


def test_addWMSRecords():
    for record in data:
        wmsMonitoringReporter.addRecord(record)
    result = wmsMonitoringReporter.commit()
    assert result["OK"]
    assert result["Value"] == len(data)


def test_addComponentRecords():
    for record in activityMonitoringData:
        componentMonitoringReporter.addRecord(record)
    result = componentMonitoringReporter.commit()
    assert result["OK"]
    assert result["Value"] == len(activityMonitoringData)


def test_addPilotSubmissionRecords():
    for record in pilotMonitoringData:
        pilotMonitoringReporter.addRecord(record)
    result = pilotMonitoringReporter.commit()
    assert result["OK"]
    assert result["Value"] == len(pilotMonitoringData)


def test_addDataOperationRecords():
    for record in dataOpMonitoringData:
        dataOpMonitoringReporter.addRecord(record)
    result = dataOpMonitoringReporter.commit()
    assert result["OK"]
    assert result["Value"] == len(dataOpMonitoringData)


@pytest.mark.parametrize(("commitFlag, delayedCommit"), [(False, False), (True, False), (True, True), (False, True)])
def test_DataOperationSender(commitFlag, delayedCommit):
    for record in dataOpMonitoringData:
        result = DataOperationSender.sendData(record, commitFlag, delayedCommit)
    assert result["OK"], result["Message"]
