"""
It is used to test the MonitoringReporter.
It requires MonitoringDB which is based on elasticsearch and MQ which is optional...

CS (not strictly necessary):

Systems
{
  Monitoring
  {
     Certification
     {
      Databases
      {
        MonitoringDB
        {
          Host = localhost
          Port = 9200
        }
      }
    }
  }
}

If you want to test with MQ:

Resources
{
  MQServices
  {
    Monitoring
    {
      MQType = Stomp
      VHost = /
      Host = xxxx.cern.ch
      Port = 61613
      User = username
      Password = xxxx
      Queues
      {
        QueueName
        {
          Acknowledgement = True
        }
      }
    }
  }
}

"""
# TODO: use WMSHistory_testData.json as in Test_MonitoringDB.py

# pylint: disable=invalid-name,wrong-import-position
import DIRAC

DIRAC.initialize()  # Initialize configuration

from DIRAC import gLogger
from DIRAC.MonitoringSystem.Client.MonitoringReporter import MonitoringReporter

gLogger.setLevel("INFO")

wmsMonitoringReporter = MonitoringReporter(monitoringType="WMSHistory")
agentMonitoringReporter = MonitoringReporter(monitoringType="AgentMonitoring")
serviceMonitoringReporter = MonitoringReporter(monitoringType="ServiceMonitoring")
pilotMonitoringReporter = MonitoringReporter(monitoringType="PilotSubmissionMonitoring")
pilotsHistoryReporter = MonitoringReporter(monitoringType="PilotsHistory")
data = [
    {
        "Status": "Waiting",
        "Jobs": 2,
        "timestamp": 1458130176000,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.GRIDKA.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049848",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458130176000,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.PIC.es",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "olupton",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458130176000,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "olupton",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458130176000,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049845",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 34,
        "timestamp": 1458141578000,
        "JobSplitType": "DataStripping",
        "MinorStatus": "unset",
        "Site": "Group.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050299",
        "UserGroup": "lhcb_data",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 120,
        "timestamp": 1458141578000,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.CERN.ch",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "mvesteri",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458141578000,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049845",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 2,
        "timestamp": 1458141578000,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049848",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458141578000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050286",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 95,
        "timestamp": 1458199202000,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "Multiple",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "mamartin",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 3,
        "timestamp": 1458199202000,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "Multiple",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "olupton",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 129,
        "timestamp": 1458199202000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "Multiple",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049844",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 5,
        "timestamp": 1458217812000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050232",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 7,
        "timestamp": 1458217812000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050234",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458217812000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 1,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050236",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 3,
        "timestamp": 1458217812000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050238",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 2,
        "timestamp": 1458217812000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.IHEP.su",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050248",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 12,
        "timestamp": 1458218413000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050248",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 5,
        "timestamp": 1458218413000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050250",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 4,
        "timestamp": 1458218413000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050251",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458218413000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.CNAF.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050280",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 24,
        "timestamp": 1458219012000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.NIKHEF.nl",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050248",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 3,
        "timestamp": 1458219012000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.NIKHEF.nl",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050251",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458222013000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.Bologna.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050303",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 7,
        "timestamp": 1458222013000,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.Bristol.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "clangenb",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 2,
        "timestamp": 1458222013000,
        "JobSplitType": "User",
        "MinorStatus": "unset",
        "Site": "LCG.Bristol.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "mrwillia",
        "JobGroup": "lhcb",
        "UserGroup": "lhcb_user",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458222013000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.Bari.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050244",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 11,
        "timestamp": 1458222013000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.Bari.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050246",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 22,
        "timestamp": 1458222013000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.Bari.it",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050248",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 23,
        "timestamp": 1458225013000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.DESYZN.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049844",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 18,
        "timestamp": 1458225013000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.DESYZN.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00049847",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458225013000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.DESYZN.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050238",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Running",
        "Jobs": 1,
        "timestamp": 1458225013000,
        "JobSplitType": "MCSimulation",
        "MinorStatus": "unset",
        "Site": "LCG.DESYZN.de",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050246",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RRCKI.ru",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050243",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RRCKI.ru",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050251",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213000,
        "JobSplitType": "MCStripping",
        "MinorStatus": "unset",
        "Site": "LCG.RRCKI.ru",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050256",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050229",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050241",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 1,
        "timestamp": 1458226213000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050243",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
    {
        "Status": "Waiting",
        "Jobs": 2,
        "timestamp": 1458226213000,
        "JobSplitType": "MCReconstruction",
        "MinorStatus": "unset",
        "Site": "LCG.RAL.uk",
        "Reschedules": 0,
        "ApplicationStatus": "unset",
        "User": "phicharp",
        "JobGroup": "00050247",
        "UserGroup": "lhcb_mc",
        "metric": "WMSHistory",
    },
]

# This dataset is used for the ComponentMonitoringType as the data which gets stored in this type
# is usually with these type of fields.
agentMonitoringData = [
    {
        "Host": "dirac-dev",
        "Agent": "SiteDirector",
        "Status": "Active",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "CycleDuration": 53,
        "Cycles": 4,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Agent": "SiteDirector",
        "Status": "Active",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "CycleDuration": 53,
        "Cycles": 4,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Agent": "SiteDirector",
        "Status": "Active",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "CycleDuration": 53,
        "Cycles": 4,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Agent": "SiteDirector",
        "Status": "Active",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "CycleDuration": 53,
        "Cycles": 4,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Agent": "SiteDirector",
        "Status": "Active",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "CycleDuration": 53,
        "Cycles": 4,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Agent": "SiteDirector",
        "Status": "Active",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "CycleDuration": 53,
        "Cycles": 4,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Agent": "SiteDirector",
        "Status": "Active",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "CycleDuration": 53,
        "Cycles": 4,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Agent": "SiteDirector",
        "Status": "Active",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "CycleDuration": 53,
        "Cycles": 4,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Agent": "SiteDirector",
        "Status": "Active",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "CycleDuration": 53,
        "Cycles": 4,
        "timestamp": 1458226213000,
    },
]
serviceMonitoringData = [
    {
        "Host": "dirac-dev",
        "Service": "Framework_SystemAdministrator",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Service": "Framework_SystemAdministrator",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Service": "Framework_SystemAdministrator",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Service": "Framework_SystemAdministrator",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Service": "Framework_SystemAdministrator",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Service": "Framework_SystemAdministrator",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Service": "Framework_SystemAdministrator",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Service": "Framework_SystemAdministrator",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213000,
    },
    {
        "Host": "dirac-dev",
        "Service": "Framework_SystemAdministrator",
        "Location": "dips://dirac-dev:9162/Framework/SystemAdministrator",
        "RunningTime": 325,
        "MemoryUsage": 345,
        "CpuPercentage": 44,
        "Connections": 92946,
        "Queries": 1880,
        "PendingQueries": 200,
        "ActiveQueries": 200,
        "RunningThreads": 200,
        "MaxFD": 200,
        "timestamp": 1458226213000,
    },
]
# Test data for the PilotMonitoring type
pilotMonitoringData = [
    {
        "HostName": "lhcbvoboxcertif00.cern.ch",
        "SiteDirector": "SiteDirector-CERN",
        "Site": "LCG.CERN.cern",
        "CE": "ce503.cern.ch",
        "Queue": "ce503.cern.ch:ce503.cern.ch-condor",
        "Status": "failed",
        "NumTotal": "10",
        "NumSucceeded": "3",
        "timestamp": 1458226213000,
    },
    {
        "HostName": "lhcbvoboxcertif00.cern.ch",
        "SiteDirector": "SiteDirector-CNAF",
        "Site": "LCG.CNAF.it",
        "CE": "ce504.cern.ch",
        "Queue": "ce504.cern.ch:ce504.cern.ch-condor",
        "Status": "failed",
        "NumTotal": "7",
        "NumSucceeded": "1",
        "timestamp": 1458226213000,
    },
]

pilotsHistoryData = [
    {
        "GridSite": "LCG.CNAF.it",
        "GridType": "",
        "Status": "failed",
        "Pilots": "7",
        "timestamp": 1649161714000,
    },
    {
        "GridSite": "LCG.CNAF.it",
        "GridType": "",
        "Status": "failed",
        "Pilots": "7",
        "timestamp": 1649161714000,
    },
]


def test_addWMSRecords():
    for record in data:
        wmsMonitoringReporter.addRecord(record)
    result = wmsMonitoringReporter.commit()
    assert result["OK"]
    assert result["Value"] == len(data)


def test_addAgentRecords():
    for record in agentMonitoringData:
        agentMonitoringReporter.addRecord(record)
    result = agentMonitoringReporter.commit()
    assert result["OK"]
    assert result["Value"] == len(agentMonitoringData)


def test_addServiceRecords():
    for record in serviceMonitoringData:
        serviceMonitoringReporter.addRecord(record)
    result = serviceMonitoringReporter.commit()
    assert result["OK"]
    assert result["Value"] == len(serviceMonitoringData)


def test_addPilotSubmissionRecords():
    for record in pilotMonitoringData:
        pilotMonitoringReporter.addRecord(record)
    result = pilotMonitoringReporter.commit()
    assert result["OK"]
    assert result["Value"] == len(pilotMonitoringData)


def test_addPilotHistoryRecords():
    for record in pilotsHistoryData:
        pilotsHistoryReporter.addRecord(record)
    result = pilotsHistoryReporter.commit()
    assert result["OK"]
    assert result["Value"] == len(pilotsHistoryData)
