#!/bin/bash -i
########################################################################
# $Header: /local/reps/dirac/DIRAC3/scripts/dirac-bash,v 1.3 2009/01/28 14:03:29 acasajus Exp $
# File :   dirac-bash
# Author : Ricardo Graciani
# Usage : dirac-bash
########################################################################
#
[ -z "$DIRACROOT" ] && export DIRACROOT=`python -c "import os,sys ; print os.path.dirname(os.path.dirname( os.path.realpath( sys.argv[1] ) ))" $0`
[ -z "$DIRACPLAT" ] && export DIRACPLAT=`$DIRACROOT/scripts/dirac-platform`

export TERMINFO=$DIRACROOT/$DIRACPLAT/share/terminfo
export PATH=$DIRACROOT/$DIRACPLAT/bin:$DIRACROOT/scripts:$PATH
if [ -z "$LD_LIBRARY_PATH" ] ; then
  export LD_LIBRARY_PATH=$DIRACROOT/$DIRACPLAT/lib:$DIRACROOT/$DIRACPLAT/lib/mysql
else
  export LD_LIBRARY_PATH=$DIRACROOT/$DIRACPLAT/lib:$DIRACROOT/$DIRACPLAT/lib/mysql:$LD_LIBRARY_PATH
fi
export PYTHONPATH=$DIRACROOT

/bin/bash --noprofile --norc -p $@
