#!/usr/bin/env python2.4
################################################################
# $Header $
################################################################

"""  This is a script to launch DIRAC agents
"""

__RCSID__ = "$Id: dirac-agent,v 1.1 2007/05/13 20:57:31 atsareg Exp $"

import sys
from DIRAC.ConfigurationSystem.Client.LocalConfiguration import LocalConfiguration
from DIRAC import gLogger, gConfig
from DIRAC.Core.Agent.AgentBase import Agent

localCfg = LocalConfiguration()

positionalArgs = localCfg.getPositionalArguments()
if len( positionalArgs ) == 0:
  gLogger.initialize( "NOT SPECIFIED", "/" )
  gLogger.fatal( "You must specify which agent to run!" )
  sys.exit(1)

agentName = positionalArgs[0]
localCfg.addMandatoryEntry( "/DIRAC/Setup" )
resultDict = localCfg.loadUserData()
if not resultDict[ 'OK' ]:
  gLogger.error( "There were errors when loading configuration", resultDict[ 'Message' ] )
  sys.exit(1)

agent = Agent(agentName)
agent.run()
