name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy_CVMFS:
    runs-on: "ubuntu-latest"
    steps:
      - uses: conda-incubator/setup-miniconda@master
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
      - name: Deploy on CVMFS
        env:
          CVMFS_PROXY_BASE64: ${{ secrets.CVMFS_PROXY_BASE64 }}
        run: |
          source /usr/share/miniconda3/etc/profile.d/conda.sh

          conda create -n CVMFS_deploy openssl=3.0.0 gct
          conda activate CVMFS_deploy

          echo "$CVMFS_PROXY_BASE64" | base64 --decode > cvmfs.proxy
          export X509_USER_PROXY=cvmfs.proxy
          export PATH=/usr/share/miniconda3/bin:/opt/conda/bin/:/opt/conda/condabin:$PATH
          type -a openssl
          openssl version
          type -a gsissh

          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keygen -R cvmfs-upload01.gridpp.rl.ac.uk
          ssh-keyscan cvmfs-upload01.gridpp.rl.ac.uk >> ~/.ssh/known_hosts

          gsissh -p 1975 -t diracgsm@cvmfs-upload01.gridpp.rl.ac.uk /home/diracsgm/cvmfs_repo/admin/sync_packages.sh -v
