name: dirac-install

on: [push, pull_request]

jobs:
  diracInstall:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.repository == 'DIRACGrid/DIRAC'

    strategy:
      fail-fast: False
      matrix:
        python:
          - 2.7.5
          - 2.7.13
          - 3.6.8
          - 3.9.4

    steps:
    - uses: actions/checkout@v3
    - name: Fail-fast for outdated pipelines
      run: .github/workflows/fail-fast.sh
    - name: prepare environment
      run: |
        conda config --set add_pip_as_python_dependency false
        conda create -c conda-forge -c free -n python_${{ matrix.python }} python=${{ matrix.python }}
    - name: run dirac-install
      run: |
        eval "$(conda shell.bash hook)" && conda activate python_${{ matrix.python }}
        python Core/scripts/dirac-install.py -l DIRAC -r integration -t server --dirac-os -ddd
